services:
  openplaylist:
    image: ghcr.io/gatorspeck/openplaylist:${OPENPLAYLIST_TAG}
    container_name: openplaylist
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    volumes:
      - ${MUSIC_PATH}:/music:ro
      - ${DATA_DIR}:/data:rw
      - ${PLEX_M3U_DROP_SOURCE}:${PLEX_M3U_DROP_SOURCE}:rw
      - ${CONFIG_PATH}:/config:rw
    restart: unless-stopped
    environment:
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_SHARED_SECRET=${LASTFM_SHARED_SECRET}
      - PLEX_ENDPOINT=${PLEX_ENDPOINT}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_LIBRARY=${PLEX_LIBRARY}
      - PLEX_MAP_SOURCE=${PLEX_MAP_SOURCE}
      - PLEX_MAP_TARGET=${PLEX_MAP_TARGET}
      - PLEX_M3U_DROP_SOURCE=${PLEX_M3U_DROP_SOURCE}
      - PLEX_M3U_DROP_TARGET=${PLEX_M3U_DROP_TARGET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ=${TZ}
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}
      - LOG_LEVEL=${LOG_LEVEL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - openplaylist_db

  openplaylist_db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

volumes:
  mariadb_data:
