services:
  openplaylist:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    volumes:
      - ${MUSIC_PATH}:/music:ro
      - ${DATA_DIR}:/data:rw
      - ${PLEX_M3U_DROP_SOURCE}:/playlist:rw
      - ${CONFIG_PATH}:/config:rw
    restart: unless-stopped
    environment:
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_SHARED_SECRET=${LASTFM_SHARED_SECRET}
      - PLEX_ENDPOINT=${PLEX_ENDPOINT}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_LIBRARY=${PLEX_LIBRARY}
      - PLEX_MAP_SOURCE=${PLEX_MAP_SOURCE}
      - PLEX_MAP_TARGET=${PLEX_MAP_TARGET}
      - PLEX_M3U_DROP_SOURCE=${PLEX_M3U_DROP_SOURCE}
      - PLEX_M3U_DROP_TARGET=${PLEX_M3U_DROP_TARGET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
