"""add playlist entry hiding persistence

Revision ID: 1667000434fb
Revises: e1f53886946f
Create Date: 2025-08-08 21:40:37.013162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1667000434fb'
down_revision: Union[str, None] = 'e1f53886946f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_entries', sa.Column('date_hidden', sa.DateTime(), nullable=True))
    op.add_column('playlist_entries', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_playlist_entries_is_hidden'), 'playlist_entries', ['is_hidden'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_entries_is_hidden'), table_name='playlist_entries')
    op.drop_column('playlist_entries', 'is_hidden')
    op.drop_column('playlist_entries', 'date_hidden')
    # ### end Alembic commands ###
