"""remove playlist unique constraint since it's too much trouble

Revision ID: 210027997761
Revises: 452de8f7c7c7
Create Date: 2025-03-31 10:16:09.607705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210027997761'
down_revision: Union[str, None] = '452de8f7c7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_entries') as batch_op:
        batch_op.drop_constraint('uq_playlist_entries_playlist_id_order', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_entries') as batch_op:
        batch_op.create_unique_constraint('uq_playlist_entries_playlist_id_order', ['playlist_id', 'order'])
    # ### end Alembic commands ###
