"""add fields for external track sources

Revision ID: 2cd52f5e6fad
Revises: b5caaba5e7d9
Create Date: 2025-07-17 20:48:35.788042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd52f5e6fad'
down_revision: Union[str, None] = 'b5caaba5e7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_files', sa.Column('last_fm_url', sa.String(length=1024), nullable=True))
    op.add_column('music_files', sa.Column('mbid', sa.String(length=50), nullable=True))
    op.add_column('music_files', sa.Column('spotify_uri', sa.String(length=1024), nullable=True))
    op.add_column('music_files', sa.Column('youtube_url', sa.String(length=1024), nullable=True))
    op.add_column('music_files', sa.Column('plex_rating_key', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_music_files_last_fm_url'), 'music_files', ['last_fm_url'], unique=False)
    op.create_index(op.f('ix_music_files_mbid'), 'music_files', ['mbid'], unique=False)
    op.create_index(op.f('ix_music_files_plex_rating_key'), 'music_files', ['plex_rating_key'], unique=False)
    op.create_index(op.f('ix_music_files_spotify_uri'), 'music_files', ['spotify_uri'], unique=False)
    op.create_index(op.f('ix_music_files_youtube_url'), 'music_files', ['youtube_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_files_youtube_url'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_spotify_uri'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_plex_rating_key'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_mbid'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_last_fm_url'), table_name='music_files')
    op.drop_column('music_files', 'plex_rating_key')
    op.drop_column('music_files', 'youtube_url')
    op.drop_column('music_files', 'spotify_uri')
    op.drop_column('music_files', 'mbid')
    op.drop_column('music_files', 'last_fm_url')
    # ### end Alembic commands ###
