"""Add scheduled tasks and playlist auto-sync fields

Revision ID: 6307b45407d0
Revises: 1667000434fb
Create Date: 2026-01-24 17:06:29.006120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6307b45407d0'
down_revision: Union[str, None] = '1667000434fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album_tracks', 'notes')
    op.alter_column('music_files', 'mbid',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('playlists', sa.Column('auto_sync_enabled', sa.Boolean(), nullable=True))
    op.add_column('playlists', sa.Column('auto_sync_schedule', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'auto_sync_schedule')
    op.drop_column('playlists', 'auto_sync_enabled')
    op.alter_column('music_files', 'mbid',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.add_column('album_tracks', sa.Column('notes', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
