"""persist album and track mbids

Revision ID: 660bb21288bf
Revises: fddadfd24416
Create Date: 2025-05-14 08:45:49.221736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660bb21288bf'
down_revision: Union[str, None] = 'fddadfd24416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('mbid', sa.String(length=50), nullable=True))
    op.add_column('lastfm_tracks', sa.Column('mbid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lastfm_tracks', 'mbid')
    op.drop_column('albums', 'mbid')
    # ### end Alembic commands ###
