"""add remote playlist snapshotting stuff

Revision ID: b5caaba5e7d9
Revises: 660bb21288bf
Create Date: 2025-06-29 20:24:15.997073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5caaba5e7d9'
down_revision: Union[str, None] = '660bb21288bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('contents', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_snapshots_id'), 'playlist_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_snapshots_last_updated'), 'playlist_snapshots', ['last_updated'], unique=False)
    op.create_index(op.f('ix_playlist_snapshots_name'), 'playlist_snapshots', ['name'], unique=False)
    op.create_table('sync_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('send_entry_adds', sa.Boolean(), nullable=True),
    sa.Column('send_entry_removals', sa.Boolean(), nullable=True),
    sa.Column('receive_entry_adds', sa.Boolean(), nullable=True),
    sa.Column('receive_entry_removals', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_targets_id'), 'sync_targets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_targets_id'), table_name='sync_targets')
    op.drop_table('sync_targets')
    op.drop_index(op.f('ix_playlist_snapshots_name'), table_name='playlist_snapshots')
    op.drop_index(op.f('ix_playlist_snapshots_last_updated'), table_name='playlist_snapshots')
    op.drop_index(op.f('ix_playlist_snapshots_id'), table_name='playlist_snapshots')
    op.drop_table('playlist_snapshots')
    # ### end Alembic commands ###
