"""initial revision

Revision ID: d4312ed97da7
Revises: 
Create Date: 2025-03-15 14:58:07.539055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4312ed97da7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlist_music_file_id', table_name='playlist_music_file')
    op.drop_table('playlist_music_file')
    op.create_index('music_file_entry_details_idx', 'playlist_entries', ['details_id'], unique=False)
    op.create_index('playlist_entries_playlist_type_order_idx', 'playlist_entries', ['playlist_id', 'entry_type', 'order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('playlist_entries_playlist_type_order_idx', table_name='playlist_entries')
    op.drop_index('music_file_entry_details_idx', table_name='playlist_entries')
    op.create_table('playlist_music_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), nullable=True),
    sa.Column('music_file_id', sa.INTEGER(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['music_file_id'], ['music_files.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playlist_music_file_id', 'playlist_music_file', ['id'], unique=False)
    # ### end Alembic commands ###
