
"""Add scheduled_tasks table

Revision ID: ddf1a1f9c947
Revises: 6307b45407d0
Create Date: 2026-01-24 17:07:28.818935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ddf1a1f9c947'
down_revision: Union[str, None] = '6307b45407d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if the table already exists before creating it
    connection = op.get_bind()
    
    # Use a more robust check for MySQL/MariaDB
    result = connection.execute(sa.text("""
        SELECT COUNT(*) as table_count 
        FROM information_schema.tables 
        WHERE table_schema = DATABASE() AND table_name = 'scheduled_tasks'
    """))
    table_exists = result.fetchone()[0] > 0
    
    if not table_exists:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('scheduled_tasks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=200), nullable=False),
            sa.Column('task_type', sa.String(length=50), nullable=False),
            sa.Column('cron_expression', sa.String(length=100), nullable=False),
            sa.Column('enabled', sa.Boolean(), nullable=True),
            sa.Column('config', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('last_run_at', sa.DateTime(), nullable=True),
            sa.Column('next_run_at', sa.DateTime(), nullable=True),
            sa.Column('total_runs', sa.Integer(), nullable=True),
            sa.Column('successful_runs', sa.Integer(), nullable=True),
            sa.Column('failed_runs', sa.Integer(), nullable=True),
            sa.Column('last_run_status', sa.String(length=20), nullable=True),
            sa.Column('last_error_message', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )
        
        # Create indexes only if table was just created
        op.create_index(op.f('ix_scheduled_tasks_enabled'), 'scheduled_tasks', ['enabled'], unique=False)
        op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
        op.create_index(op.f('ix_scheduled_tasks_name'), 'scheduled_tasks', ['name'], unique=False)
        op.create_index(op.f('ix_scheduled_tasks_task_type'), 'scheduled_tasks', ['task_type'], unique=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Check if the table exists before trying to drop it
    connection = op.get_bind()
    
    # Use a more robust check for MySQL/MariaDB
    result = connection.execute(sa.text("""
        SELECT COUNT(*) as table_count 
        FROM information_schema.tables 
        WHERE table_schema = DATABASE() AND table_name = 'scheduled_tasks'
    """))
    table_exists = result.fetchone()[0] > 0
    
    if table_exists:
        # ### commands auto generated by Alembic - please adjust! ###
        try:
            op.drop_index(op.f('ix_scheduled_tasks_task_type'), table_name='scheduled_tasks')
        except:
            pass  # Index may not exist
        try:
            op.drop_index(op.f('ix_scheduled_tasks_name'), table_name='scheduled_tasks')
        except:
            pass  # Index may not exist
        try:
            op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
        except:
            pass  # Index may not exist
        try:
            op.drop_index(op.f('ix_scheduled_tasks_enabled'), table_name='scheduled_tasks')
        except:
            pass  # Index may not exist
        op.drop_table('scheduled_tasks')
        # ### end Alembic commands ###
