"""move external source columns around

Revision ID: e1f53886946f
Revises: 040031d31856
Create Date: 2025-08-03 12:46:38.509094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f53886946f'
down_revision: Union[str, None] = '040031d31856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album_tracks', 'notes')
    op.add_column('music_files', sa.Column('last_fm_url', sa.String(length=1024), nullable=True))
    op.add_column('music_files', sa.Column('spotify_uri', sa.String(length=1024), nullable=True))
    op.add_column('music_files', sa.Column('youtube_url', sa.String(length=1024), nullable=True))
    op.add_column('music_files', sa.Column('mbid', sa.String(length=50), nullable=True))
    op.add_column('music_files', sa.Column('plex_rating_key', sa.String(length=1024), nullable=True))
    op.drop_index('ix_music_files_new_album', table_name='music_files')
    op.drop_index('ix_music_files_new_album_artist', table_name='music_files')
    op.drop_index('ix_music_files_new_artist', table_name='music_files')
    op.drop_index('ix_music_files_new_exact_release_date', table_name='music_files')
    op.drop_index('ix_music_files_new_length', table_name='music_files')
    op.drop_index('ix_music_files_new_publisher', table_name='music_files')
    op.drop_index('ix_music_files_new_rating', table_name='music_files')
    op.drop_index('ix_music_files_new_release_year', table_name='music_files')
    op.drop_index('ix_music_files_new_title', table_name='music_files')
    op.drop_index('ix_music_files_new_year', table_name='music_files')
    op.create_index(op.f('ix_music_files_album'), 'music_files', ['album'], unique=False)
    op.create_index(op.f('ix_music_files_album_artist'), 'music_files', ['album_artist'], unique=False)
    op.create_index(op.f('ix_music_files_artist'), 'music_files', ['artist'], unique=False)
    op.create_index(op.f('ix_music_files_exact_release_date'), 'music_files', ['exact_release_date'], unique=False)
    op.create_index(op.f('ix_music_files_length'), 'music_files', ['length'], unique=False)
    op.create_index(op.f('ix_music_files_publisher'), 'music_files', ['publisher'], unique=False)
    op.create_index(op.f('ix_music_files_rating'), 'music_files', ['rating'], unique=False)
    op.create_index(op.f('ix_music_files_release_year'), 'music_files', ['release_year'], unique=False)
    op.create_index(op.f('ix_music_files_title'), 'music_files', ['title'], unique=False)
    op.create_index(op.f('ix_music_files_year'), 'music_files', ['year'], unique=False)
    op.drop_index('ix_track_genres_new_genre', table_name='track_genres')
    op.drop_index('ix_track_genres_new_id', table_name='track_genres')
    op.create_index(op.f('ix_track_genres_genre'), 'track_genres', ['genre'], unique=False)
    op.create_index(op.f('ix_track_genres_id'), 'track_genres', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_genres_id'), table_name='track_genres')
    op.drop_index(op.f('ix_track_genres_genre'), table_name='track_genres')
    op.create_index('ix_track_genres_new_id', 'track_genres', ['id'], unique=False)
    op.create_index('ix_track_genres_new_genre', 'track_genres', ['genre'], unique=False)
    op.drop_index(op.f('ix_music_files_year'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_title'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_release_year'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_rating'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_publisher'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_length'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_exact_release_date'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_artist'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_album_artist'), table_name='music_files')
    op.drop_index(op.f('ix_music_files_album'), table_name='music_files')
    op.create_index('ix_music_files_new_year', 'music_files', ['year'], unique=False)
    op.create_index('ix_music_files_new_title', 'music_files', ['title'], unique=False)
    op.create_index('ix_music_files_new_release_year', 'music_files', ['release_year'], unique=False)
    op.create_index('ix_music_files_new_rating', 'music_files', ['rating'], unique=False)
    op.create_index('ix_music_files_new_publisher', 'music_files', ['publisher'], unique=False)
    op.create_index('ix_music_files_new_length', 'music_files', ['length'], unique=False)
    op.create_index('ix_music_files_new_exact_release_date', 'music_files', ['exact_release_date'], unique=False)
    op.create_index('ix_music_files_new_artist', 'music_files', ['artist'], unique=False)
    op.create_index('ix_music_files_new_album_artist', 'music_files', ['album_artist'], unique=False)
    op.create_index('ix_music_files_new_album', 'music_files', ['album'], unique=False)
    op.drop_column('music_files', 'plex_rating_key')
    op.drop_column('music_files', 'mbid')
    op.drop_column('music_files', 'youtube_url')
    op.drop_column('music_files', 'spotify_uri')
    op.drop_column('music_files', 'last_fm_url')
    op.add_column('album_tracks', sa.Column('notes', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
